language: node_js
node_js:
   - "0.10"

env:
  - PRELOAD_APP_DATA=diy PRELOAD_APP_MARKET=release
  - PRELOAD_APP_DATA=diy PRELOAD_APP_MARKET=beta
  - PRELOAD_APP_DATA=diy PRELOAD_APP_MARKET=alpha
#  - PRELOAD_APP_DATA=demos PRELOAD_APP_MARKET=beta
  - PRELOAD_APP_DATA=demos PRELOAD_APP_MARKET=alpha

services:
  - couchdb

before_script:
  - npm install gardener -g
  - npm install garden-core -g

script: 
  - make && make upload

notifications:
  #webhooks: 
    #urls:
    #  - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    #on_success: change
    #on_failure: always
  #email:
  #  recipients:
  #    - milan@medicmobile.org

